#!/usr/bin/env python

import sys
import re
from os import listdir, getcwd
from os.path import join, getsize

is_block = re.compile('^blk\d+\.dat$')
number = re.compile('\d+|$')


def main():
    data_dir = getcwd()
    need_size = 1 # 1G
    total_size = 0
    if len(sys.argv) > 1:
        need_size = int(sys.argv[1])
    if len(sys.argv) > 2:
        data_dir = sys.argv[2]
    need_size = need_size * pow(1024, 3)
    all_files = [f for f in listdir(data_dir) if is_block.match(f)]
    all_files = sorted(all_files, key=get_block_number, reverse=True)
    for file in all_files:
        filepath = join(data_dir, file)
        total_size += getsize(filepath)
        print(file)
        if total_size > need_size:
            break


def get_block_number(filename):
    return number.findall(filename)[0]


main()
